version: '2'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./.data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker_db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8182:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql